name = "cloudinary-worker-images"
main = "src/index.ts"
compatibility_date = "2023-02-20"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ORIGIN = "pub-52a608aa13f042fdb7b162d6f2f3dfb2.r2.dev"
WORKER_HOST = "cloudinary-worker-images.geniecode.workers.dev"
CLOUDINARY_CLOUD = "dmgccwn3j"
CLOUDINARY_API_KEY = "828149249888378"
CLOUDINARY_API_SECRET = "WH7IsLy5-MlLftWAg54sMccao1Q"